server:
  port: 9999

chaos:
  monkey:
    enabled: true
    watcher:
      service: false
      controller: false
      repository: false
      restController: true
    assaults:
      level: 3
      latencyActive: true
      latencyRangeStart: 3
      latencyRangeEnd: 10
      exceptionsActive: true