server:
    port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

chaos:
  monkey:
    enabled: true
    watcher:
      service: false
      controller: false
      repository: false
      restController: true
    assaults:
      level: 3
      latencyActive: true
      latencyRangeStart: 3
      latencyRangeEnd: 10
      exceptionsActive: true